import Head from 'next/head'

type Props = {
  title: string
}

export default function Home({ title = 'Rect Avançado' }: Props) {
  return (
    <div className="container">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>{title}</p>
      </main>

      <footer className="footer">
        <p>Rodapé</p>
      </footer>
    </div>
  )
}
